export * from './types';
export * from './geometry';
export { ManifestError, parseManifest } from './manifest';
export { observeRect } from './observe-rect';
export { scrollIntoViewIfNeeded } from './scroll-into-view';
export { isVisible } from './visibility';
export { matchAnchor } from './anchors';
export { findElementById, resolveElement } from './resolve';
export type { ResolveOutcome } from './resolve';
export { waitForElement } from './wait-for-element';
export { LexicalIntentResolver, tokenize } from './intent';
export type { IntentMatch, IntentResolver } from './intent';
export { buildSessionUpdate } from './agent-session';
export type { SessionUpdate, SessionOptions, ToolDefinition } from './agent-session';
export { ToolGate } from './tool-gate';
export type { ToolResultFrame } from './tool-gate';
export { DriftTracker, MAX_CORRECTIONS, QUEST_TTL_MS, correctionInstruction, correctionText } from './drift';
export type { CorrectionContext, LitRole, Quest } from './drift';
